// UI-testing sample payloads for the Report and Analytics pages. Driven by the
// "Sample data" toggle on each page (no fetch happens while it is on) so the full
// visual surface renders without a live Elasticsearch pipeline (dev has none —
// TODO-M01-023 / TODO-M01-026). Deterministic values only — no Date.now/randomness —
// so screenshots and E2E assertions stay stable. NOT wired into any production path.

import type { SurveyAnalytics } from "./analytics-api"
import type { SurveyReport } from "./report-api"
import type { TrendEvent } from "../components/AnalyticsTrendChart"

export const SAMPLE_REPORT: SurveyReport = {
  period: { resolvedFrom: "2026-07-13T00:00:00Z", resolvedTo: "2026-07-20T00:00:00Z" },
  metricCards: {
    responses: 2154,
    completionRate: 81.4,
    medianTimeSeconds: 264,
    touchpoints: 6,
  },
  headlineKpis: {
    csat: { value: 82, target: 85, deltaPp: 2.6 },
    nps: { value: 42, target: 50, deltaPp: -1.8 },
    ces: { value: 34, target: 30, deltaPp: 0.9 },
  },
  perQuestion: [
    {
      questionId: "sample-q-kpi",
      questionText: "How satisfied were you with the loan disbursement?",
      kpiId: "csat",
      type: "Kpi",
      subtype: null,
      kind: "kpi_bar_gauge",
      responsesCount: 2101,
      distribution: [
        { label: "5 — Very satisfied", count: 894, pctOfRespondents: null },
        { label: "4", count: 671, pctOfRespondents: null },
        { label: "3", count: 302, pctOfRespondents: null },
        { label: "2", count: 148, pctOfRespondents: null },
        { label: "1 — Very dissatisfied", count: 86, pctOfRespondents: null },
      ],
      respondentsBase: null,
      gauge: { value: 82, target: 85 },
      average: null,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-scale",
      questionText: "How helpful was the branch staff?",
      type: "Scale",
      subtype: "Stars",
      kind: "scale_gauge",
      responsesCount: 1987,
      distribution: [
        { label: "5 stars", count: 743, pctOfRespondents: null },
        { label: "4 stars", count: 611, pctOfRespondents: null },
        { label: "3 stars", count: 356, pctOfRespondents: null },
        { label: "2 stars", count: 181, pctOfRespondents: null },
        { label: "1 star", count: 96, pctOfRespondents: null },
      ],
      respondentsBase: null,
      gauge: { value: 76, target: 80 },
      average: null,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-single",
      questionText: "Which channel did you use to apply?",
      type: "SingleSelect",
      subtype: "List",
      kind: "donut",
      responsesCount: 2043,
      distribution: [
        { label: "Branch visit", count: 812, pctOfRespondents: null },
        { label: "Mobile app", count: 654, pctOfRespondents: null },
        { label: "Call centre", count: 388, pctOfRespondents: null },
        { label: "Website", count: 189, pctOfRespondents: null },
      ],
      respondentsBase: null,
      gauge: null,
      average: null,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-yesno",
      questionText: "Did the disbursement arrive within the promised time?",
      type: "YesNo",
      subtype: null,
      kind: "donut",
      responsesCount: 2120,
      distribution: [
        { label: "Yes", count: 1791, pctOfRespondents: null },
        { label: "No", count: 329, pctOfRespondents: null },
      ],
      respondentsBase: null,
      gauge: null,
      average: null,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-multi",
      questionText: "Which of the following did you use during the process? (select all that apply)",
      type: "MultiSelect",
      subtype: null,
      kind: "bars_respondents",
      responsesCount: 1874,
      distribution: [
        { label: "Fast service", count: 1206, pctOfRespondents: 64.4 },
        { label: "Friendly staff", count: 1044, pctOfRespondents: 55.7 },
        { label: "Clear information", count: 715, pctOfRespondents: 38.2 },
        { label: "Short queue", count: 498, pctOfRespondents: 26.6 },
        { label: "Accessible location", count: 331, pctOfRespondents: 17.7 },
      ],
      respondentsBase: 1874,
      gauge: null,
      average: null,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-text",
      questionText: "What could we improve about the disbursement experience?",
      type: "InputField",
      subtype: "Paragraph",
      kind: "verbatims",
      responsesCount: 763,
      distribution: null,
      respondentsBase: null,
      gauge: null,
      average: null,
      sample: [
        {
          responseId: "sample-v-1",
          channel: "WhatsApp",
          submittedAt: "2026-07-18T09:24:00Z",
          text: "The branch team resolved my request in under ten minutes — genuinely impressive turnaround.",
        },
        {
          responseId: "sample-v-2",
          channel: "Email",
          submittedAt: "2026-07-17T14:02:00Z",
          text: "Waiting time was long and the ticket screen was confusing. The staff were helpful once it was my turn.",
        },
        {
          responseId: "sample-v-3",
          channel: "WhatsApp",
          submittedAt: "2026-07-16T19:41:00Z",
          text: "Please add more self-service kiosks — the app covers most needs but deposits still require the counter.",
        },
      ],
      totalAvailable: 47,
    },
    {
      questionId: "sample-q-number",
      questionText: "How many days did the full process take?",
      type: "InputField",
      subtype: "Number",
      kind: "numeric_line",
      responsesCount: 692,
      avgUnit: "days",
      numberAxis: "Number of days",
      distribution: [
        { label: "0–2", count: 58, pctOfRespondents: null },
        { label: "3–5", count: 214, pctOfRespondents: null },
        { label: "6–8", count: 251, pctOfRespondents: null },
        { label: "9–11", count: 118, pctOfRespondents: null },
        { label: "12+", count: 51, pctOfRespondents: null },
      ],
      respondentsBase: null,
      gauge: null,
      average: 6.4,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-matrix",
      questionText: "How would you rate each aspect of the service?",
      type: "Matrix",
      subtype: "CustomColumns",
      kind: "none",
      responsesCount: 1655,
      distribution: null,
      respondentsBase: null,
      gauge: null,
      average: null,
      sample: null,
      totalAvailable: null,
    },
    {
      questionId: "sample-q-ranking",
      questionText: "Rank these features by how important they are to you.",
      type: "Ranking",
      subtype: null,
      kind: "none",
      responsesCount: 1512,
      distribution: null,
      respondentsBase: null,
      gauge: null,
      average: null,
      sample: null,
      totalAvailable: null,
    },
  ],
}

export const SAMPLE_ANALYTICS: SurveyAnalytics = {
  period: {
    resolvedFrom: "2026-07-13T00:00:00Z",
    resolvedTo: "2026-07-20T00:00:00Z",
    granularity: "daily",
  },
  funnel: {
    sent: {
      count: 4820,
      pctOfSent: null,
      deltaPct: 12.4,
      deltaPp: null,
      conversionFromPrevStagePct: null,
    },
    opened: {
      count: 3480,
      pctOfSent: 72.2,
      deltaPct: null,
      deltaPp: 1.8,
      conversionFromPrevStagePct: 72.2,
    },
    started: {
      count: 2610,
      pctOfSent: 54.1,
      deltaPct: null,
      deltaPp: -0.6,
      conversionFromPrevStagePct: 75.0,
    },
    finished: {
      count: 2154,
      pctOfSent: 44.7,
      deltaPct: null,
      deltaPp: 2.1,
      conversionFromPrevStagePct: 82.5,
    },
  },
  overallCompletionRate: { valuePct: 44.7, deltaPp: 2.1 },
  channels: [
    { channel: "WhatsApp", sent: 2410, completionRate: 0.52, deltaPp: 3.1 },
    { channel: "Email", sent: 1465, completionRate: 0.38, deltaPp: -1.2 },
    { channel: "SMS", sent: 640, completionRate: 0.31, deltaPp: 0.4 },
    { channel: "QR code", sent: 305, completionRate: 0.61, deltaPp: null },
  ],
  trend: [
    { bucketStart: "2026-07-13T00:00:00Z", sent: 512, finished: 198, completionRate: 0.3867 },
    { bucketStart: "2026-07-14T00:00:00Z", sent: 668, finished: 274, completionRate: 0.4102 },
    { bucketStart: "2026-07-15T00:00:00Z", sent: 705, finished: 302, completionRate: 0.4284 },
    { bucketStart: "2026-07-16T00:00:00Z", sent: 590, finished: 271, completionRate: 0.4593 },
    { bucketStart: "2026-07-17T00:00:00Z", sent: 742, finished: 348, completionRate: 0.469 },
    { bucketStart: "2026-07-18T00:00:00Z", sent: 803, finished: 391, completionRate: 0.4869 },
    { bucketStart: "2026-07-19T00:00:00Z", sent: 421, finished: 189, completionRate: 0.4489 },
    { bucketStart: "2026-07-20T00:00:00Z", sent: 379, finished: 181, completionRate: 0.4776 },
  ],
}

/** Sample action markers so the trend chart's ReferenceDot/Line annotations render
 * (no real event source exists yet — TODO-M01-029). */
export const SAMPLE_TREND_EVENTS: TrendEvent[] = [
  { bucketStart: "2026-07-15T00:00:00Z", label: "IVR redesign live" },
  { bucketStart: "2026-07-18T00:00:00Z", label: "Reminder wave sent" },
]
